Repository Bibeo-shop/back, pull requests merged in 2024-06, with the labels that each got.

#2 chore: typeorm 연결
  package.json
  src/app.module.ts
  yarn.lock
Labels: 초기세팅

#3 feat: entity 생성
  package.json
  src/points/entities/point.entity.ts
  src/shipping-address/entities/shipping-address.entity.ts
  src/user-coupons-status/entities/user-coupons-status.entity.ts
  src/user-coupons/entities/user-coupon.entity.ts
  src/user-permissions/entities/user-permission.entity.ts
  src/user-points/entities/user-point.entity.ts
  src/user-shipping-address/entities/user-shipping-address.entity.ts
  src/users/entities/user.entity.ts
  yarn.lock
Labels: 초기세팅

#5 chore: nodemon 의존성 설치
  package.json
  yarn.lock
Labels: 초기세팅

#4 fix: user entity 비밀번호 필드 길이 수정
  src/users/entities/user.entity.ts
Labels: 초기세팅

#6 feat: 유저 회원가입 기능 구현
  package.json
  src/app.module.ts
  src/main.ts
  src/users/dto/create-user.dto.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  src/utils/messages.ts
  yarn.lock
Labels: 기능 구현

#7 feat: entity 생성
  src/app.module.ts
  src/cart-status/entities/cart-status.entity.ts
  src/carts/entities/cart.entity.ts
  src/categories/entities/category.entity.ts
  src/coupon-issuance-mode/entities/coupon-issuance-mode.entity.ts
  src/coupon-status/entities/coupon-status.entity.ts
  src/coupons/entities/coupon.entity.ts
  src/expiration-date-status/entities/expiration-date-status.entity.ts
  src/order-products/entities/order-product.entity.ts
  src/orders/entities/order.entity.ts
  src/point-policy/entities/point-policy.entity.ts
  src/products/entities/product.entity.ts
  src/purchases-point-status/entities/purchases-point-status.entity.ts
  src/review-point-status/entities/review-point-status.entity.ts
  src/user-coupons-status/entities/user-coupons-status.entity.ts
  src/user-coupons/entities/user-coupon.entity.ts
  src/users/entities/user.entity.ts
Labels: 초기세팅

#8 feat: 빠진 entity 생성
  src/carts/entities/cart.entity.ts
  src/product-options/entities/product-option.entity.ts
  src/product-status/entities/product-status.entity.ts
  src/products/entities/product.entity.ts
Labels: 초기세팅

#9 feat: users test 추가
  package.json
  src/app.module.ts
  src/auth/auth.guard.spec.ts
  src/auth/auth.guard.ts
  src/user-permissions/user-permission.module.ts
  src/user-permissions/user-permissions.service.spec.ts
  src/user-permissions/user-permissions.service.ts
  src/users/user-role.enum.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  tsconfig.json
  yarn.lock
Labels: 테스트 작성

#10 feat: category-status entity 생성
  src/categories/entities/category.entity.ts
  src/category-status/entities/category-status.entity.ts
Labels: 초기세팅
